Proyecto para prueba de Doxygen: cripto.cc File Reference
cripto.cc File Reference
Universidad de La Laguna Escuela Superior de Ingeniería y Tecnología Grado en Ingeniería Informática Informática Básica.
#include <fstream>
#include <iostream>
#include <string>
#include "funciones_cripto.h"
Functions
void EncriptarCesar (std::string fichero_entrada, std::string fichero_salida, int key)
Universidad de La Laguna Escuela Superior de Ingeniería y Tecnología Grado en Ingeniería Informática Informática Básica.
void DesencriptarCesar (std::string fichero_entrada, std::string fichero_salida, int key)
Realiza el descifrado César a una cadenana de texto dada una constante de desplazamiento.
void EncriptarXor (std::string fichero_entrada, std::string fichero_salida, int key)
void UsoPrograma (int argc, char *argv[])
Muestra el uso correcto del programa Si el uso no es correcto muestra un mensaje y finaliza la ejecución.
int main (int argc, char *argv[])
Función principal.
Detailed Description
Universidad de La Laguna Escuela Superior de Ingeniería y Tecnología Grado en Ingeniería Informática Informática Básica.
Author
MuhammadCampos Preira
Date
16.dec.2020
Encripta o desencripta un archivo usando el método XOR o César, guardando la salida en otro archivo.
Definition in file cripto.cc.
Function Documentation
DesencriptarCesar()
void DesencriptarCesar (std::string fichero_entrada, std::string fichero_salida, int key)
Realiza el descifrado César a una cadenana de texto dada una constante de desplazamiento.
Parameters
[in] archivo_entrada archivo a decodificar
[in] archivo_salida archivo decodificado
[in] key numero de desplazamientos
Definition at line 50 of file funciones_cripto.cc.
{
   std::ifstream archivo_entrada{fichero_entrada};
   std::ofstream archivo_salida{fichero_salida};
   while(archivo_entrada){
     std::string linea_actual;
     std::getline(archivo_entrada, linea_actual);
     for(int i = 0; i < linea_actual.length(); ++i){
         linea_actual[i] -= key;
     }
     archivo_salida << linea_actual << std::endl;
   }
 }
Referenced by main().
EncriptarCesar()
void EncriptarCesar (std::string fichero_entrada, std::string fichero_salida, int key)
Universidad de La Laguna Escuela Superior de Ingeniería y Tecnología Grado en Ingeniería Informática Informática Básica.
Author
Muhammad Campos Preira
Date
16.dec.2020
Funciones utilizadas en el programa cripto.cc Realiza el cifrado César a una cadenana de texto dada una constante de desplazamiento
Parameters
[in] archivo_entrada archivo a codificar
[in] archivo_salida archivo codificado
[in] key numero de desplazamientos
Definition at line 25 of file funciones_cripto.cc.
{
   std::ifstream archivo_entrada{fichero_entrada};
   std::ofstream archivo_salida{fichero_salida};
   while(archivo_entrada){
     std::string linea_actual;
     std::getline(archivo_entrada, linea_actual);
     for(int i = 0; i < linea_actual.length(); ++i){
         linea_actual[i] += key;
     }
     archivo_salida << linea_actual << std::endl;
   }
 }
Referenced by main().
EncriptarXor()
void EncriptarXor (std::string fichero_entrada, std::string fichero_salida, int key)
Referenced by main().
main()
int main (int argc, char * argv[])
Función principal.
Parameters
[in] argc Número de parámetros de línea de comandos
[in] argv Vector que contiene los parámetros de la linea de comandos
Definition at line 31 of file cripto.cc.
{
   std::string fichero_entrada{argv[1]};
   std::string fichero_salida{argv[2]};
   std::string password = argv[4];
   int metodo{argv[3][0]};
   int key = 0;
   char operacion{argv[5][0]};
   if (metodo == '2')
     key = std::stoi(password);
   if (metodo == '2') {
     if (operacion == '+') {
       EncriptarCesar(fichero_entrada, fichero_salida, key);
     } else if (operacion == '-') {
       DesencriptarCesar(fichero_entrada, fichero_salida, key);
     }
   }
   if (metodo == '1') {
     if (operacion == '+' || operacion == '-') {
       EncriptarXor(fichero_entrada, fichero_salida, key);
     }
   }
   return 0;
 }
References DesencriptarCesar(), EncriptarCesar(), and EncriptarXor().
UsoPrograma()
void UsoPrograma (int argc, char * argv[])
Muestra el uso correcto del programa Si el uso no es correcto muestra un mensaje y finaliza la ejecución.
Parameters
[in] argc Número de parámetros de línea de comandos
[in] argv Vector (char*) que contiene los parámetros
Definition at line 101 of file funciones_cripto.cc.